import hashlib
import json
import logging
from datetime import datetime, timezone
from io import BytesIO
from uuid import UUID, uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app.db.models.job_match import JobMatch
from app.db.models.job_match_report import JobMatchReport
from app.services import storage_service

logger = logging.getLogger(__name__)

REPORT_VERSION = "1.0.0"


def calculate_report_hash(match: JobMatch) -> str:
    """
    Compute a unique SHA-256 hash of the analysis results + report version
    to check for modifications and facilitate reuse of existing reports.
    """
    payload = {
        "match_score": match.match_score,
        "ats_score": match.ats_score,
        "strengths": match.strengths,
        "missing_keywords": match.missing_keywords,
        "missing_skills": match.missing_skills,
        "recommendations": match.recommendations,
        "role_fit": match.role_fit,
        "interview_readiness": match.interview_readiness,
        "summary": match.summary,
        "job_title": match.job_title,
        "company_name": match.company_name,
        "report_version": REPORT_VERSION,
    }
    serialized = json.dumps(payload, sort_keys=True, default=str)
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


# ── PDF Drawings / Canvas Handlers ───────────────────────────────────────────

def draw_first_page(canvas, doc):
    canvas.saveState()
    # Premium bottom thin separator
    canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
    canvas.setLineWidth(0.5)
    canvas.line(54, 50, 542, 50)

    # Footer
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.drawString(54, 38, "Generated by InterviewAI")
    canvas.drawRightString(542, 38, f"Page {doc.page}")
    canvas.restoreState()


def draw_later_page(canvas, doc):
    canvas.saveState()
    # Premium Header line & Title
    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(colors.HexColor("#475569"))
    canvas.drawString(54, 800, "InterviewAI  |  Job Match Report")
    canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
    canvas.setLineWidth(0.5)
    canvas.line(54, 792, 542, 792)

    # Footer
    canvas.line(54, 50, 542, 50)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.drawString(54, 38, "Generated by InterviewAI")
    canvas.drawRightString(542, 38, f"Page {doc.page}")
    canvas.restoreState()


# ── PDF Story Builder ─────────────────────────────────────────────────────────

def build_pdf_story(match: JobMatch, resume_filename: str) -> bytes:
    buffer = BytesIO()

    # Document setup: A4 with 0.75 inch (54pt) margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=72,
    )

    styles = getSampleStyleSheet()

    # Custom premium typography styling
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0f172a"),  # slate-900
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#475569"),  # slate-600
        spaceAfter=20,
    )
    h2_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=14,
        spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor("#334155"),  # slate-700
        spaceAfter=8,
    )
    summary_body_style = ParagraphStyle(
        "SummaryBody",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=11,
        leading=16,
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=10,
    )
    label_style = ParagraphStyle(
        "MetricLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#64748b"),
        alignment=1,  # Center
    )
    score_value_style = ParagraphStyle(
        "ScoreValue",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        textColor=colors.HexColor("#0f172a"),
        alignment=1,  # Center
    )

    story = []

    # ──────────────────────────────────────────────────────────────────────────
    # PAGE 1: Hero, Scores, Executive Summary
    # ──────────────────────────────────────────────────────────────────────────

    story.append(Spacer(1, 25))
    story.append(Paragraph("Job Match Report", subtitle_style))
    story.append(Paragraph(match.job_title or "Target Role Match", title_style))
    if match.company_name:
        story.append(Paragraph(f"Analysis against parameters for {match.company_name}", subtitle_style))
    story.append(Spacer(1, 15))

    # Match and ATS Score side-by-side Table
    score_data = [
        [
            Paragraph("JOB MATCH SCORE", label_style),
            Paragraph("ATS COMPATIBILITY", label_style),
        ],
        [
            Paragraph(f"{match.match_score}%", score_value_style),
            Paragraph(f"{match.ats_score}%", score_value_style),
        ],
    ]
    # Width constraint: 595pt (A4) - 108pt (margins) = 487pt printable
    score_table = Table(score_data, colWidths=[243, 244])
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("TOPPADDING", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
                ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#e2e8f0")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ]
        )
    )
    story.append(score_table)
    story.append(Spacer(1, 35))

    # Executive Match Summary
    story.append(Paragraph("Executive Summary", h2_style))
    story.append(Paragraph(match.summary, summary_body_style))

    # Page Break to Page 2
    story.append(PageBreak())

    # ──────────────────────────────────────────────────────────────────────────
    # PAGE 2: Keywords, Skills, Recommendations
    # ──────────────────────────────────────────────────────────────────────────

    story.append(Spacer(1, 10))
    story.append(Paragraph("Keyword & Skill Analysis", title_style))
    story.append(Spacer(1, 10))

    # Keywords side-by-side card
    matched_kws = ", ".join(match.strengths) if match.strengths else "None detected"
    missing_kws = ", ".join(match.missing_keywords) if match.missing_keywords else "None detected"

    kw_data = [
        [
            Paragraph("<b>Matched Keywords</b>", body_style),
            Paragraph("<b>Missing Keywords</b>", body_style),
        ],
        [
            Paragraph(matched_kws, body_style),
            Paragraph(missing_kws, body_style),
        ],
    ]
    kw_table = Table(kw_data, colWidths=[243, 244])
    kw_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0fdf4")),  # subtle green
                ("BACKGROUND", (1, 0), (1, -1), colors.HexColor("#fef2f2")),  # subtle red
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("LINEBEFORE", (1, 0), (1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#e2e8f0")),
            ]
        )
    )
    story.append(kw_table)
    story.append(Spacer(1, 20))

    # Missing Skills
    story.append(Paragraph("Missing Skill Gaps", h2_style))
    skills_text = ", ".join(match.missing_skills) if match.missing_skills else "No major skill gaps identified"
    story.append(Paragraph(skills_text, body_style))
    story.append(Spacer(1, 20))

    # Recommendations
    story.append(Paragraph("Actionable Resume Recommendations", h2_style))
    for i, rec in enumerate(match.recommendations):
        # Heuristic Impact mapping
        impact_str = "High Impact" if i == 0 else "Medium Impact" if i == 1 else "Low Impact"
        impact_color = "#b91c1c" if i == 0 else "#b45309" if i == 1 else "#047857"

        rec_item_text = (
            f"<b>{i+1}. {rec}</b><br/>"
            f"<font size=8 color='{impact_color}'><b>{impact_str.upper()}</b></font>"
        )
        story.append(Paragraph(rec_item_text, body_style))
        story.append(Spacer(1, 6))

    # Page Break to Page 3
    story.append(PageBreak())

    # ──────────────────────────────────────────────────────────────────────────
    # PAGE 3: Role Fit, Interview Readiness, Metadata
    # ──────────────────────────────────────────────────────────────────────────

    story.append(Spacer(1, 10))
    story.append(Paragraph("Detailed Match Narrative", title_style))
    story.append(Spacer(1, 10))

    # Role Fit Narrative
    story.append(Paragraph("Role Fit Analysis", h2_style))
    story.append(Paragraph(match.role_fit, body_style))
    story.append(Spacer(1, 20))

    # Interview Readiness
    story.append(Paragraph("Interview Readiness & Preparation Focus", h2_style))
    story.append(Paragraph(match.interview_readiness, body_style))
    story.append(Spacer(1, 40))

    # Metadata Card
    metadata_data = [
        [
            Paragraph("<b>REPORT METADATA</b>", label_style),
            Paragraph("", label_style),
        ],
        [
            Paragraph("Resume Used:", body_style),
            Paragraph(resume_filename, body_style),
        ],
        [
            Paragraph("Generated Date:", body_style),
            Paragraph(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"), body_style),
        ],
        [
            Paragraph("Report Engine Version:", body_style),
            Paragraph(REPORT_VERSION, body_style),
        ],
    ]
    metadata_table = Table(metadata_data, colWidths=[150, 337])
    metadata_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("SPAN", (0, 0), (1, 0)),
                ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#e2e8f0")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ]
        )
    )
    story.append(metadata_table)

    # Build document
    doc.build(
        story,
        onFirstPage=draw_first_page,
        onLaterPages=draw_later_page,
    )

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


# ── Service Actions ───────────────────────────────────────────────────────────

async def generate_and_upload_report(
    session: AsyncSession,
    *,
    match: JobMatch,
    resume_filename: str,
    profile_id: UUID,
) -> JobMatchReport:
    """
    Orchestrate report lifecycle:
    1. Calculate report content hash
    2. Check for report hash reuse in DB
    3. Generate premium ReportLab PDF bytes
    4. Store report PDF in private 'reports' bucket
    5. Save metadata record to job_match_reports
    """
    report_hash = calculate_report_hash(match)

    # Check for report hash reuse to avoid duplicate files & DB rows
    dup_stmt = select(JobMatchReport).where(
        JobMatchReport.report_hash == report_hash,
        JobMatchReport.profile_id == profile_id,
    )
    dup_res = await session.execute(dup_stmt)
    existing_report = dup_res.scalar_one_or_none()

    if existing_report is not None:
        logger.info(
            "Reusing existing report %s (hash match: %s)",
            existing_report.id,
            report_hash,
        )
        return existing_report

    # Generate PDF bytes
    pdf_bytes = build_pdf_story(match, resume_filename)

    # Upload to Supabase Storage private 'reports' bucket
    report_uuid = uuid4()
    storage_path = f"reports/{profile_id}/job-match/{report_uuid}.pdf"

    await storage_service.upload_file(
        object_path=storage_path,
        data=pdf_bytes,
        content_type="application/pdf",
    )

    # Save metadata record in DB
    report_row = JobMatchReport(
        id=report_uuid,
        job_match_id=match.id,
        profile_id=profile_id,
        report_path=storage_path,
        report_version=REPORT_VERSION,
        report_hash=report_hash,
    )
    session.add(report_row)
    await session.flush()

    logger.info(
        "Generated and saved new report %s for match %s (hash=%s)",
        report_row.id,
        match.id,
        report_hash,
    )
    return report_row


async def get_signed_report_url(
    session: AsyncSession,
    *,
    match_id: UUID,
    profile_id: UUID,
) -> str | None:
    """
    Retrieve time-limited signed download URL for the report associated with match_id.
    """
    stmt = (
        select(JobMatchReport)
        .where(
            JobMatchReport.job_match_id == match_id,
            JobMatchReport.profile_id == profile_id,
        )
        .order_by(JobMatchReport.created_at.desc())
        .limit(1)
    )
    res = await session.execute(stmt)
    report = res.scalar_one_or_none()

    if report is None:
        return None

    return await storage_service.get_signed_url(report.report_path, expires_in=600)
